<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>agilium_manager_azure_business</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle" Version="1.8.9" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.32" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="3.1.32" />
  </ItemGroup>
 
</Project>
